### ISSUE TITLE
"Show x more" link on >4 summaries takes you to landing page if not on p1 of summaries

### ISSUE THREAD

**Issue by dajare** [topanswers/topanswers#10]
The new limit to 4 answers on summary pages is nice, with the "show *n* more" link. That link works great if on page 1 of the summaries - TeX.TA has an example as I write: find "[To-do list before going public][1]".

IF however, the summaries are on page >1, then the "show *n* more" link takes you to the landing page. There's an example on page 5 on the TeX.TA site (use link above -- seems there is no way to "permalink" other pages? no obvious way, at any rate!) and find "What should the site icon be?": its "show 8 more" link takes you to the landing page, rather than expanding the summary list.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6 (Mojave)
 - Browser: FF v. 72.0.2 

**Additional context**  
Relates to [commit 423c1c1][c]

[1]: https://topanswers.xyz/tex
[c]: https://github.com/topanswers/topanswers/commit/423c1c19d434cf2c39aaead4612b9f14db582c9d

**Comment by jackdouglas** [comment]
Thanks very much, this is fixed by commit c3892b7bfa140b9743fe170010738b7794f1437d
