### ISSUE TITLE
Make the markdown editor pages layout responsive

### ISSUE THREAD

**Issue by jackdouglas** [topanswers/topanswers#12]
If the screen is wide enough the 3-column view for editing answers is best, but this should adapt to a 2-column view with the question above, and then finally to a single-column view as the viewport narrows.

Reference: https://topanswers.xyz/meta?q=228

**Comment by alerque** [comment]
This will be a lot easier to code if you start with the one column layout as the lowest common denominator then add break points that add column layout styles as the viewport gets wider (as opposed to trying to strip layout code out as it gets smaller).

**Comment by jackdouglas** [comment]
fixed by commits 4275bf72896ac6b0d73ddffe2c0c8e36992d3f16 and 9981ede2cbcc3d4893764709b2e73ab43bb82ef5
