### ISSUE TITLE
Implement filtering options for questions

### ISSUE THREAD

**Issue by jackdouglas** [topanswers/topanswers#14]
References: https://topanswers.xyz/answer?id=365, https://topanswers.xyz/meta?q=485, https://topanswers.xyz/meta?q=500

**Comment by abrudz** [comment]
I suggest adding `[`*tagName*`]` to search to filter for only posts with a given tag (and clicking on a tag should automatically replace the search field with this text. This matches SE functionality.

I suggest adding `{`*postType*`}` to search to filter for only posts of a given type with a given tag (and clicking on a post type box should automatically replace the search field with this text. (`{}` could search for the generic post type if applicable.)

**Comment by jackdouglas** [comment]
implemented by 8cb8b644c0a56ad8f13c97702d3e55ce33f3f3bb

thanks for the syntax suggestions @abrudz, we've implemented them as you suggested — though please note we haven't (yet) implemented the 'click on tag/label to search' suggestions you made (https://topanswers.xyz/meta?q=694 and https://topanswers.xyz/meta?q=696)
