### ISSUE TITLE
Enhance internal site navigation

### ISSUE THREAD

**Issue by dajare** [topanswers/topanswers#29]
https://topanswers.xyz/meta?q=652 | Reported by Monica | 2020-01-31

When in the context of a specific Q&A, two problems arise: 

1. Using the browser's "back" function is not guaranteed to take you "back" to your original context if, e.g., you were previously on Page >1 in the Q&A summaries; and
2. There are no navigational links to take you elsewhere within that TA community.

On SE sites, the left sidebar handles (most) "inner" community navigation, and the top-right icon-dropdown gives you site-level links (plus "help") for the network.

*Something* like this analogy would be most helpful on TA, too. This may mean having a second line of nav in the topbar, or rethinking use of the rest of the screen real-estate. Wherever/however it is managed, it seems like a needed development to enhance ease-of-use and comfort levels on the site.

**Comment by JamesRDouglas** [comment]
The second problem is now fixed:

1. There is a TA homepage link at the top left of every page
2. There is also a community homepage just to the right of the TA link
3. The site selector dropdown is now also on every page

**Comment by jackdouglas** [comment]
fixed by ca7f31873a0557b7e34a32b1e7b6fc13a7f5d073, thanks for being patient :)
