### ISSUE TITLE
Tag adding window is too narrow and focus chops entry

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#30]
![image](https://user-images.githubusercontent.com/10961427/74690457-1af05d00-51d7-11ea-9d3e-c5abbc5f3509.png)

**Comment by jackdouglas** [comment]
we switched to the native datalist control with 963bd1714d34f5783975aa14226d9477cca2cb9d — datalist isn't perfect but is an improvement and fixes this bug.
