### ISSUE TITLE
Inconsistent code block rendering on mobile

### ISSUE THREAD

**Issue by petervandivier** [topanswers/topanswers#32]
**Describe the bug**

In some scenarios, code blocks will not render on mobile (see iOS screencap below)

Anecdotally, posts with multiple code blocks or large code blocks seem affected, but I have not done a rigorous survey at this time.

**To Reproduce**

> TODO: inventory a few sample posts with unexpected code block rendering behaviour on mobile

**Expected behavior**

Code blocks should render or display informative error message in all scenarios.

**Screenshots**

![image](https://user-images.githubusercontent.com/10898767/74720646-025f6180-522e-11ea-92e8-2b3fee11c4d9.png)

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS 13.3.1
 - Browser Chrome
 - Version 80.0.3987.95

**Comment by jackdouglas** [comment]
I had a similar issue which was I thought was resolved with `-webkit-transform: translate3d(0, 0, 0);` (commit 393aae5).

That seems to have caused more problems than it solved however.

The new tweak (commit 01bd55607b8ebb59a8291493a5a8b59e27193beb) just released seems to do a better all-round job — please can you confirm if the issue has now gone away for you?

**Comment by petervandivier** [comment]
The issue appears to no longer be affecting my device.
