### ISSUE TITLE
First messages in new main chat room are invisible until page is refreshed

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#35]
**Describe the bug**
When a new chat main room is created, the first messages written there seem to disappear when entered. They only show up after relaoding the page.

**To Reproduce**
1. Create a new main (not post) chat room
2. Enter a message there
3. Notice that the message doesn't show up in the chat log
4. Reload page to reveal messages

**Expected behavior**
All messages should render immediately.

**Desktop (please complete the following information):**
 - OS: Windows
 - Firefox
 - Version 73.0

**Comment by JamesRDouglas** [comment]
fixed by commit afc288131c6b1b778bef91b3935c8d16c2d56661
