### ISSUE TITLE
Insert-image button hides typed text in chat box

### ISSUE THREAD

**Issue by dajare** [topanswers/topanswers#39]
The new button for inserting images into chat doesn't seem to "respect" text being typed into the box:

![Selection_523](https://user-images.githubusercontent.com/40625/75241114-6bf6e700-57bd-11ea-8a6c-1c471641c196.png)

It's hardly fatal, but it is off-putting!

- FF 73.0 (64-bit)
- Ubuntu 18.04 LTS

**Comment by jackdouglas** [comment]
fixed by commit 0ec912c0e540fe98947b31a873675020e69fcc19
