### ISSUE TITLE
Same text and background in return-to-question link on edit review page

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#43]
`rgb(var(--rgb-dark))` text on same background
![image](https://user-images.githubusercontent.com/10961427/75417529-2f47fe80-5929-11ea-8062-25755332cf83.png)

**Comment by JamesRDouglas** [comment]
fixed by commit [`8043f43`](https://github.com/topanswers/topanswers/commit/8043f43e9c21f5f6cb804a4a4f549e65986338f1)
