### ISSUE TITLE
Site selector's "about" links have disappeared

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#44]
![image](https://user-images.githubusercontent.com/10961427/75417867-ee041e80-5929-11ea-9575-7695817e243f.png)

**Comment by JamesRDouglas** [comment]
This is intentional, as the about link now appears in the header of every site that has one.

**Comment by abrudz** [comment]
@jackdouglas Once TA has plenty of sites (Think SE's 174), I might want to browse the list (will it scroll?) and if a title looks interesting, jump straight to the "more info" page, rather than having to do two page loads.

**Comment by JamesRDouglas** [comment]
fixed with commit 3be34b08ac6861ce35a0141b639816f9ccdf469a
