### ISSUE TITLE
Same text and background in return-to-question link on edit page

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#45]
`rgb(var(--rgb-dark))` text on same background
![image](https://user-images.githubusercontent.com/10961427/75519130-72be6d80-59fa-11ea-88a0-f6cf2266d132.png)

**Comment by JamesRDouglas** [comment]
fixed by commit [`06fa712`](https://github.com/topanswers/topanswers/commit/06fa712b2078d92c6bd903071d9a8af73ce94281)
