### ISSUE TITLE
Same text and background in return-to-question/answer links on history page

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#46]
`rgb(var(--rgb-dark))` text on same background
![image](https://user-images.githubusercontent.com/10961427/75540239-8aeeb680-5a13-11ea-9c92-6df30158d68f.png)

**Comment by JamesRDouglas** [comment]
fixed by commit [`06fa712`](https://github.com/topanswers/topanswers/commit/06fa712b2078d92c6bd903071d9a8af73ce94281)
