### ISSUE TITLE
Notification about how many stars I can award is off by one

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#47]
The number of stars one can award is equal to the number of digits in one's star count, 1-9:1, 10-99:2, 100-999:3, etc. but the system congratulates on one star less than the truth:

![image](https://user-images.githubusercontent.com/10961427/75540762-942c5300-5a14-11ea-85ce-2155b3d223dd.png)

**Comment by JamesRDouglas** [comment]
fixed by commit 65c78c85b80539b8393d4a40cbf8bdb79abd4c95
