### ISSUE TITLE
Find the home of / a home for qp

### ISSUE THREAD

**Issue by alerque** [topanswers/topanswers#5]
Hey @jackdouglas where did `get/lib/qp/*` originate? Is it published anywhere?

Working on #3 (see #4) and need to know where to fetch that from. Anything that is best served as minified JS clearly came from somewhere else. In the node world [`qp`](https://www.npmjs.com/package/qp) is already something else. We don't have to publish qp as an npm package (although there is a good chance that's a good venue for it) but we do need it to be somewhere.

**Comment by jackdouglas** [comment]
It's from here: https://github.com/JustinPealing/html-query-plan/releases

I'm not actually sure which version we are using!
