### ISSUE TITLE
Link colour on homepage

### ISSUE THREAD

**Issue by samcarter** [topanswers/topanswers#53]
**Describe the bug**

The links on the home page https://topanswers.xyz/ are hard to see (and in the footline even invisible)

**Screenshots**

![Screen Shot 2020-03-05 at 16 26 59](https://user-images.githubusercontent.com/43832342/75996605-63f62000-5efe-11ea-95cf-998119b6ae63.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Firefox ESR, Firefox 73 and Opera

**Comment by jackdouglas** [comment]
ouch, thanks for spotting that!

fixed with commit bd9d09d4ca8920bf368cc84acb50cb0c96676e5f
