### ISSUE TITLE
Bad contrast in star display if I give a star to a chat message

### ISSUE THREAD

**Issue by joulev** [topanswers/topanswers#55]
**Describe the bug**
If I give a star to a chat message, the number of stars becomes very hard to read in some sites (I haven't tested other sites yet).

**Expected behavior**
The contrast should be increased for the text to be more readable. 

**Screenshots**
Some examples:
https://topanswers.xyz/cplusplus:
![image](https://user-images.githubusercontent.com/44609036/76678134-02be0300-6608-11ea-99f0-1f1eeca4013b.png)
https://topanswers.xyz/tex:
![image](https://user-images.githubusercontent.com/44609036/76678138-09e51100-6608-11ea-93a0-f9e140d121f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Browser: Opera v67.0.3575.53.

**Comment by jackdouglas** [comment]
Thanks @joulev, we've tweaked the theme colours for both C++ and TeX to improve the contrast

**Comment by joulev** [comment]
@jackdouglas Thanks and sorry for keeping this open. I noticed the change but as I rarely went to GitHub, I didn't close this issue 😃.
