### ISSUE TITLE
Security Issue: API Key Exposed

### ISSUE THREAD

**Issue by jbis9051** [topanswers/topanswers#71]
https://github.com/topanswers/topanswers/blob/818f34e2584dda2468e8c58ca25d3981b1f61efb/post/profile.php#L30

The stackexchange API key is exposed here

**Comment by jackdouglas** [comment]
Appreciate you taking a look @jbis9051, but there is no security issue here:

> Pass this as key when making requests against the Stack Exchange API to receive a higher request quota.
>
> ***This is not considered a secret, and may be safely embed in client side code or distributed binaries***

We do have a "Client Secret" from SE too:

> This must be kept secret. Do not embed it in client side code or binaries you intend to distribute. If you need client side authentication, use the implicit OAuth 2.0 flow. 

This is safely stored in the database in the `one` table. The schema is published here, and some dummy seed data, but nothing of any importance is exposed: https://github.com/topanswers/topanswers/blob/master/sql/seed/one

**Comment by jbis9051** [comment]
Ah. I assumed the API key shouldn't be public but I was wrong.

However, from a development standpoint I think a config file or environment variable would be a better place to store it. Makes it easier and simpler to setup a new instance (with a different key).

**Comment by jackdouglas** [comment]
> However, from a development standpoint I think a config file or environment variable would be a better place to store it. Makes it easier and simpler to setup a new instance (with a different key).

yes, probably — we'll move it to the database (there isn't any real reason why it should be in the code)
