### ISSUE TITLE
Key's stored in repo

### ISSUE THREAD

**Issue by jbis9051** [topanswers/topanswers#72]
I didn't check if these are the one's live on the site, but the `https://github.com/topanswers/topanswers/tree/master/docker/apache/cert` directory has the private key. They seem to be references in the docker and apache config.

Dockerfile:
```
COPY cert /etc/cert/topanswers.local
```

Apache Config: 
```
 SSLEngine on
    SSLCertificateFile /etc/cert/topanswers.local/cert.pem
    SSLCertificateKeyFile /etc/cert/topanswers.local/key.pem
```

----

**Update**: These are not the live certs but they still shouldn't be here.

**Comment by jackdouglas** [comment]
again, thanks for taking a look at the repo here it is appreciated

> I didn't check if these are the one's live on the site

they aren't, they are dummy keys created for convenience for people wanting to spin up a test environment, a la 'snake oil'

**Comment by paxcodes** [comment]
>Update: These are not the live certs but they still shouldn't be here.

@jbis9051 Curious to know why you think they shouldn't be there although they are not live certs. As I said to Jack when he asked me about the certs,

> I don’t think [it matters that cert key is exposed] because the certificate is only used for local development. 
>
> SSL needs to be set up for the TA cookies to work properly. I added it to remove a step for devs interested in contributing. 

The top answer [here](https://security.stackexchange.com/a/105824) is perhaps a similar reasoning to our certificate being only used for local dev environments.

There is the concept of the ["decay" of intentions](https://security.stackexchange.com/a/106018) that has to be considered. Aside from that, I wonder what else should be factored in when deciding whether or not to keep this in the repo.

**Comment by jbis9051** [comment]
@paxcodes  From a security perspective, I don't think its too much of an issue as they aren't valid trusted certificates.

At a minimum, the keys existence should be mentioned in any documentation.

If I intended to setup my own instance, I would have to clone this repo and modify the docker file or the Apache config file to use my own certificates (unless I am missing something). Instead, I prefer the approach of storing the path to the keys in environment variables. This is consistent with the approach of a couple other open source projects I have seen. The other option, of course, is a configuration file.

Just my opinion.
