### ISSUE TITLE
Everything broken

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#77]
In reaction to https://topanswers.xyz/transcript?room=1&id=55669&year=2020&month=6#c55669 it seems everything is now broken. I can write messages or posts.

**Comment by jackdouglas** [comment]
ouch, thanks, I've pushed a hotfix that unbreaks chat, will look at posts now

**Comment by jackdouglas** [comment]
posts seem to be fixed too. I'm glad you have this channel to contact me when TA is broken!

**Comment by jackdouglas** [comment]
actually this still breaks, looking again

**Comment by jackdouglas** [comment]
phew, now actually fixed I think
