### ISSUE TITLE
Diff-view in history interprets inline code as maths

### ISSUE THREAD

**Issue by Skillmon** [topanswers/topanswers#8]
**Describe the bug**
When looking at the edit history of some posts one can look at a handy diff-view showing what changed in that specific edit. In that diff-view inline code is interpreted as maths, e.g., `lipsum` will render as `lip` and a `\sum` symbol.

**To Reproduce**
1. Go to https://topanswers.xyz/answer-history?id=664
2. Scroll down to the first diff
3. See error

**Expected behavior**
I expected a correct interpretation of the markdown to show inline code formatting.

**Screenshots**
![previewbug](https://user-images.githubusercontent.com/8701017/73123818-632fad00-3f94-11ea-997d-75bfee5298dd.png)

**Desktop:**
 - OS: Arch Linux
 - Browser FF
 - Version 72.0.2-1 from the Arch repos

**Comment by jackdouglas** [comment]
Thanks, this is fixed with https://github.com/topanswers/topanswers/commit/823ad9ef521793437c23ba49bb4629c9a5f9db8a
