### ISSUE TITLE
More (all?) user icons should link to the user profile page.

### ISSUE THREAD

**Issue by jackdouglas** [topanswers/topanswers#81]

**Comment by joulev** [comment]
... and usernames too, I think.

**Comment by jackdouglas** [comment]
my hesitation about making usernames link to profiles too is that we'd then want to underline them (we are trying to be consistent about that) — and it will affect the look of the site considerably

it is quite rare for a username to be alone (ie not accompanied by a user icon)

**Comment by jackdouglas** [comment]
completed with f4acad14
