### ISSUE TITLE
Erratic chat in Safari 13.1.* of MacOS 10.14.6

### ISSUE THREAD

**Issue by paxcodes** [topanswers/topanswers#87]
**To Reproduce**
1. Use Safari 13.1.1 of MacOS 10.14.6
2. Visit topanswers.com/meta

**Actual Behaviour**
1) Chat oneboxing is not working
2) Weird font

![Screen Shot 2020-07-16 at 6 04 27 AM](https://user-images.githubusercontent.com/13646646/87674704-367e7600-c72b-11ea-9391-6d6af98a2922.png)

3) When I refresh, chat is no longer available. Exact steps for this:
     a) Go to meta.ta
     b) Type something in the chat box
     c) Try to submit the message by pressing `Enter` (it won't submit)
     d) Since you are having trouble submitting the message (see step c), you try to refresh.
     e) After refreshing you see a blank chat.
     
![Screen Shot 2020-07-16 at 6 11 56 AM](https://user-images.githubusercontent.com/13646646/87674752-4ac27300-c72b-11ea-821c-9875d57ae24c.png)

**Expected behavior**
- In the first screenshot, you should see onebox of a youtube video and topanswer question
- In the second screenshot, it should contain chat messages, etc.

**Comment by jackdouglas** [comment]
are you still seeing this behaviour, I can't currently repro it on Safari 13.1.2 on MacOS 10.14.6…

**Comment by paxcodes** [comment]
Updated Safari.

Now, when I load "Sandbox" existing messages do not render properly. But messages submitted after the page has loaded do:

![Screen Shot 2020-07-16 at 8 39 42 AM](https://user-images.githubusercontent.com/13646646/87691939-05f50700-c740-11ea-84ce-b94b126b2bac.png)

I then went to `meta` to check again whether it also happens there and I get the "blank" chat. (see screenshot in first post)

**Comment by jackdouglas** [comment]
hmmm, I don't get that in the sandbox either — but the unrendered text is a sign that there has been a JS error, is there anything in the console?

**Comment by joulev** [comment]
> hmmm, I don't get that in the sandbox either — but the unrendered text is a sign that there has been a JS error, is there anything in the console?

I sometimes get this issue too, but on mobile only. Not sure how to open the console though (Edge running in iOS). And the issue only happens occasionally, not all the time.

![936D718B-DA8D-4BE4-868F-85F9941EF356](https://user-images.githubusercontent.com/44609036/87700605-ccb0ab80-c7c0-11ea-8dd6-c6e31837f4ee.jpeg)

**Comment by jackdouglas** [comment]
@joulev debugging on mobile is generally a pain — though I just found out that Chrome on iOS can capture console output: https://9to5google.com/2019/03/25/chrome-ios-debugging-tool, which might help us track this sort of thing down

**Comment by paxcodes** [comment]
Can't reproduce this in Safari anymore.

**Comment by jackdouglas** [comment]
we think this might have been fixed with 612f87af7f4574576c9f70cdac01235a2a9feb64, thanks @paxcodes :)
