### ISSUE TITLE
Drafts not showing on the main feed of webserver.ta

### ISSUE THREAD

**Issue by paxcodes** [topanswers/topanswers#89]
**Describe the bug**
Drafts are not showing on the main feed of webserver.ta

**To Reproduce**
1. In webserver.ta, ask a question
2. Write stuff
3. Save it as draft. You will be led to the Q page (topanswers.xyz/webserver?q=XXXX)
4. Go to the main feed (topanswers.xyz/webserver)

**Expected behavior**
The main feed will list the draft: "DRAFT: Title of question I'm working on"

**Actual behavior**
The main feed does not list the draft. If the author of the draft did not note the link, the draft will be "lost"

**Desktop:**
 - OS: MacOS 10.14.6
 - Browser: 
    - Brave Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (x86_64)
    - Firefox 80.0.1 (64-bit)

**Current workarounds**
- Look at devtools localstorage.
- Make sure to note the link of the draft to be able to retrieve it.

**Comment by jackdouglas** [comment]
Thanks Pax

This is by design (drafts are now only visible on your private profile). Link to discussion on TA: https://topanswers.xyz/transcript?room=1&id=78435#c78435
