### ISSUE TITLE
Old TA icon in Q#1

### ISSUE THREAD

**Issue by paxcodes** [topanswers/topanswers#90]
**Describe the bug**
Old TA logo in Question#1

**To Reproduce**
1. Go to https://topanswers.xyz/meta?q=1

**Expected behavior**
It will have the latest TA logo?

**Screenshots**
![Screen Shot 2020-10-21 at 1 11 11 PM](https://user-images.githubusercontent.com/13646646/96777235-edc80000-139e-11eb-9174-692617f0b06a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Brave

**Comment by jackdouglas** [comment]
Nice find! Rooms (even question rooms) can have a custom icon — this one did and it never got changed until now. 

I've put the new logo on instead though perhaps it should just get the default generated one, idk :)
